### ISSUE TITLE
".withLocalPlugin" is not adding the plugin to book.json 

### ISSUE THREAD

**Issue by SamyPesse** [todvora/gitbook-tester#2]
`.withLocalPlugin(path)` should add the plugin (after reading the `package.json`) to the `book.json` .

**Comment by todvora** [comment]
Should be fixed in 1.0.2 release. Thanks for the bug-report!

**Comment by SamyPesse** [comment]
Still not working with `1.0.2`, If I remove this line (https://github.com/GitbookIO/plugin-superscript/blob/master/test/index.js#L9), tests are failing.

But maybe it's better to force the developer to explicitly list his plugin.

**Comment by todvora** [comment]
You are right, I just fixed that too in ```1.0.3```. Testing is hard and everything that makes it easier and can be done automatically should be probably done by default.
